In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
print(a[1][1])
np.shape(a)

5


(3, 3)

In [5]:
b = np.array([[10,20,30],[40,50,60],[70,80,90]])

In [6]:
a + b

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [7]:
a - b

array([[ -9, -18, -27],
       [-36, -45, -54],
       [-63, -72, -81]])

In [8]:
a * b  # mengalikan elemen yang sama posisinya

array([[ 10,  40,  90],
       [160, 250, 360],
       [490, 640, 810]])

In [9]:
a@b  # perkalian matriks

array([[ 300,  360,  420],
       [ 660,  810,  960],
       [1020, 1260, 1500]])

In [10]:
2*a

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [11]:
a / b   # pembagian antar elemen yang sama posisinya

array([[0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1]])

In [12]:
a**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [13]:
a > 3   # mencari nilai matriks yang memenuhi 

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [14]:
a.T             # Transpose matriks
a.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [15]:
c = np.zeros((3,4))   #membuat matriks yang isinya 0
print(c)

d = np.ones((3,4))    #membuat matriks yang isinya 1
print(f'\n{d}')

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
e = np.eye((3))     # membuat identity matriks
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
diag_a = np.diag(a)     # mencari diagonal dari matriks
print(diag_a)

trace_a = np.trace(a)       # penjumlahan dari diagonal matriks
print(trace_a)

[1 5 9]
15


In [18]:
f = np.linspace(1,100,10)
print(f)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [19]:
g = np.tile(a, (2,3))       # untuk mengulangi matriks a sebanyak 2,3
print(g)

[[1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6]
 [7 8 9 7 8 9 7 8 9]
 [1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6]
 [7 8 9 7 8 9 7 8 9]]


In [20]:
h = np.concatenate((a,b),1)     # menggabungkan matriks secara horizontal
print(h)                        # atau bisa juga menggunakan np.hstack

i = np.concatenate((a,b))       # menggabungkan matriks secara vertikal
print(i)                        # atau bisa juga menggunakan np.vstack

[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]
 [ 7  8  9 70 80 90]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]
 [40 50 60]
 [70 80 90]]


In [21]:
det_a = np.linalg.det(a)        # mencari determinan matriks
print(det_a)

contoh_matriks = np.array([[1,2],[3,4]])
det_matriks = np.linalg.det(contoh_matriks)
print(int(det_matriks))

invers_matriks = np.linalg.pinv(contoh_matriks)     # mencari invers matriks
print(invers_matriks)

print(contoh_matriks@invers_matriks)

0.0
-2
[[-2.   1. ]
 [ 1.5 -0.5]]
[[ 1.00000000e+00 -6.66133815e-16]
 [ 8.88178420e-16  1.00000000e+00]]


In [22]:
j = np.linalg.norm(a)
print(j)

# penjelasan darimana norm di dapat

k = np.sqrt(np.sum(a**2))
print(k)

16.881943016134134
16.881943016134134


In [27]:
# Di python juga bisa menggunakan .matrix
l = np.matrix('1,2,3;4,5,6;7,8,9')
print(l)

if np.sum(l) == np.sum(a):
    print('True')

[[1 2 3]
 [4 5 6]
 [7 8 9]]
True
